name: muzikplaya
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-64.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.4+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  on_audio_query: ^2.6.1
  permission_handler: ^9.2.0
  marquee: ^2.2.1
  flutter_screenutil: ^5.5.3+2
  move_to_background: ^1.0.2
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.4
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true
  assets:
  - assets/